---
services:
  relayer:
    build:
      context: ../../
      dockerfile: Dockerfile.development
    ports:
      - 8080:8080/tcp
    environment:
      REDIS_URL: ${REDIS_URL}
      RATE_LIMIT_REQUESTS_PER_SECOND: 10
      RATE_LIMIT_BURST: 50
      WEBHOOK_SIGNING_KEY: ${WEBHOOK_SIGNING_KEY}
      API_KEY: ${API_KEY}
      CDP_API_KEY_SECRET: ${CDP_API_KEY_SECRET}
      CDP_WALLET_SECRET: ${CDP_WALLET_SECRET}
    security_opt:
      - no-new-privileges
    networks:
      - relayer-network
      - metrics-network
    volumes:
      - ./config:/app/config/
      - ../../config/networks:/app/config/networks
    depends_on:
      - redis
    restart: on-failure:5
  redis:
    image: redis:bookworm
    ports:
      - 6379:6379/tcp
    security_opt:
      - no-new-privileges
    volumes:
      - redis_data:/data
    command:
      - redis-server
      - --appendonly
      - 'yes'
      - --save
      - '60'
      - '1'
    networks:
      - relayer-network
      - metrics-network
    restart: on-failure:5
networks:
  metrics-network:
    internal: true
  relayer-network:
    driver: bridge
volumes:
  redis_data:
    driver: local
